#ifndef VIDEO_PLAYER_AVFOUNDATION_FVPVIDEOPLAYERPLUGIN_H
#define VIDEO_PLAYER_AVFOUNDATION_FVPVIDEOPLAYERPLUGIN_H

#import <Flutter/Flutter.h>

@interface FVPVideoPlayerPlugin : NSObject <FlutterPlugin>
@end

#endif /* VIDEO_PLAYER_AVFOUNDATION_FVPVIDEOPLAYERPLUGIN_H */
