#ifndef FLUTTER_LOCAL_NOTIFICATIONS_FLUTTERLOCALNOTIFICATIONSPLUGIN_H
#define FLUTTER_LOCAL_NOTIFICATIONS_FLUTTERLOCALNOTIFICATIONSPLUGIN_H

#import <Flutter/Flutter.h>

@interface FlutterLocalNotificationsPlugin : NSObject <FlutterPlugin>
@end

#endif /* FLUTTER_LOCAL_NOTIFICATIONS_FLUTTERLOCALNOTIFICATIONSPLUGIN_H */
