#ifndef RECEIVE_SHARING_INTENT_RECEIVESHARINGINTENTPLUGIN_H
#define RECEIVE_SHARING_INTENT_RECEIVESHARINGINTENTPLUGIN_H

#import <Flutter/Flutter.h>

@interface ReceiveSharingIntentPlugin : NSObject <FlutterPlugin>
@end

#endif /* RECEIVE_SHARING_INTENT_RECEIVESHARINGINTENTPLUGIN_H */
