#ifndef FLUTTER_SECURE_STORAGE_FLUTTERSECURESTORAGEPLUGIN_H
#define FLUTTER_SECURE_STORAGE_FLUTTERSECURESTORAGEPLUGIN_H

#import <Flutter/Flutter.h>

@interface FlutterSecureStoragePlugin : NSObject <FlutterPlugin>
@end

#endif /* FLUTTER_SECURE_STORAGE_FLUTTERSECURESTORAGEPLUGIN_H */
