#ifndef FLUTTER_FOREGROUND_TASK_FLUTTERFOREGROUNDTASKPLUGIN_H
#define FLUTTER_FOREGROUND_TASK_FLUTTERFOREGROUNDTASKPLUGIN_H

#import <Flutter/Flutter.h>

@interface FlutterForegroundTaskPlugin : NSObject <FlutterPlugin>
@end

#endif /* FLUTTER_FOREGROUND_TASK_FLUTTERFOREGROUNDTASKPLUGIN_H */
