#ifndef SHARED_PREFERENCES_FOUNDATION_SHAREDPREFERENCESPLUGIN_H
#define SHARED_PREFERENCES_FOUNDATION_SHAREDPREFERENCESPLUGIN_H

#import <Flutter/Flutter.h>

@interface SharedPreferencesPlugin : NSObject <FlutterPlugin>
@end

#endif /* SHARED_PREFERENCES_FOUNDATION_SHAREDPREFERENCESPLUGIN_H */
